FROM node:22-alpine

RUN apk add --no-cache dumb-init

RUN addgroup -g 1001 -S nodejs && \
    adduser -S adonisjs -u 1001

WORKDIR /app

COPY package*.json ./

RUN npm ci

RUN chown -R adonisjs:nodejs /app

USER adonisjs

EXPOSE 3333

ENTRYPOINT ["dumb-init", "--"]

CMD ["npm", "run", "dev"]